### ISSUE TITLE
Add loading gif when loading recommendations or creating playlist

### ISSUE THREAD

**Issue by RyanRussell00** [RyanRussell00/personal-dj#1]
When the user clicks on "Get Recommendations" there should be something (such as a gif) that lets the user know that it's loading and whether it was a success or failure.

**Comment by RyanRussell00** [comment]
I've changed the text of the buttons to "loading" when they're loading but I'd like an actual gif or something that ends with success or failure.

**Comment by astriskit** [comment]
let me send PR for this!

**Comment by astriskit** [comment]
@RyanRussell00 - I'm unable to test my changes due to limitations of `.env`; 
Any ideas on how to proceed? 

<strike>Anyways I'm going to open a PR and then you let me know the results - so as to change it further;</strike>

I'd suggest, though, for making it a faster feedback loop - try using sort of build pipeline;

Update: I'll defer doing anything, until you respond.

**Comment by RyanRussell00** [comment]
@astriskit 
In the [GETTING_STARTED](https://github.com/RyanRussell00/personal-dj/blob/master/GETTING-STARTED.md) I outline the steps for setting up the necessary .env variables to run it locally.

The reasons I haven't setup a build pipeline yet is:
1) I need to write tests
2) The secrets are not visible to anyone who forks the repo, which means they need to setup their own secrets.

I've made an issue for myself on GitHub to create a build pipeline and set up all this stuff. Thanks for your input!

Let me know if you still want to take on this issue.

**Comment by astriskit** [comment]
Ok - @RyanRussell00 - will take this up.

**Comment by RyanRussell00** [comment]
@astriskit Fantastic, thank you! I've also added the Hacktoberfest label to this issue.
