### ISSUE TITLE
Add more customized inputs for recommendations

### ISSUE THREAD

**Issue by RyanRussell00** [RyanRussell00/personal-dj#20]
The [Spotify Web API for recommendations](https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/) offers the option to add more inputs, such as:
- acousticness
- instrumentalness
- speechiness
- tempo
- valence (Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).)

**Note:** These should all be optional inputs.

**Comment by harshalitalele** [comment]
Hey,
I will take a look at this one!

**Comment by RyanRussell00** [comment]
@harshalitalele Great, thank you!

**Comment by sonamdh1** [comment]
Hi @RyanRussell00 ! I have created a PR for this issue - https://github.com/RyanRussell00/personal-dj/pull/33
Please check and let me know if any changes are required.

Though this issue seems to have been already assigned, since the comments were from 2 days, I gave it a try. Seems like a nice project.
